apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}-web
spec:
  selector: { app: {{ include "odoo.fullname" . }}, tier: web }
  ports:
    - port: 80
      targetPort: 8069
      name: http
